package org.dragard.projectmanager.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-31T04:14:36.429+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "AuthorizationEndpointImplService",
                  wsdlLocation = "http://localhost:9090/task-manager/auth?wsdl",
                  targetNamespace = "http://endpoint.projectmanager.dragard.org/")
public class AuthorizationEndpointImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.projectmanager.dragard.org/", "AuthorizationEndpointImplService");
    public final static QName AuthorizationEndpointImplPort = new QName("http://endpoint.projectmanager.dragard.org/", "AuthorizationEndpointImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9090/task-manager/auth?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AuthorizationEndpointImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:9090/task-manager/auth?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AuthorizationEndpointImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuthorizationEndpointImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthorizationEndpointImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AuthorizationEndpointImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AuthorizationEndpointImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AuthorizationEndpointImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AuthorizationEndpointImpl
     */
    @WebEndpoint(name = "AuthorizationEndpointImplPort")
    public AuthorizationEndpointImpl getAuthorizationEndpointImplPort() {
        return super.getPort(AuthorizationEndpointImplPort, AuthorizationEndpointImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthorizationEndpointImpl
     */
    @WebEndpoint(name = "AuthorizationEndpointImplPort")
    public AuthorizationEndpointImpl getAuthorizationEndpointImplPort(WebServiceFeature... features) {
        return super.getPort(AuthorizationEndpointImplPort, AuthorizationEndpointImpl.class, features);
    }

}
