
package org.dragard.projectmanager.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-01T15:23:27.268+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "Exception", targetNamespace = "http://endpoint.projectmanager.dragard.org/")
public class Exception_Exception extends java.lang.Exception {

    private org.dragard.projectmanager.endpoint.Exception exception;

    public Exception_Exception() {
        super();
    }

    public Exception_Exception(String message) {
        super(message);
    }

    public Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, org.dragard.projectmanager.endpoint.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, org.dragard.projectmanager.endpoint.Exception exception, java.lang.Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public org.dragard.projectmanager.endpoint.Exception getFaultInfo() {
        return this.exception;
    }
}
