package org.dragard.projectmanager.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-29T11:40:25.870+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.projectmanager.dragard.org/", name = "ProjectEndpointImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface ProjectEndpointImpl {

    @WebMethod
    @Action(input = "http://endpoint.projectmanager.dragard.org/ProjectEndpointImpl/getViewProjectRequest", output = "http://endpoint.projectmanager.dragard.org/ProjectEndpointImpl/getViewProjectResponse")
    @RequestWrapper(localName = "getViewProject", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.GetViewProject")
    @ResponseWrapper(localName = "getViewProjectResponse", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.GetViewProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.dragard.projectmanager.endpoint.Response getViewProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.projectmanager.dragard.org/ProjectEndpointImpl/createProjectRequest", output = "http://endpoint.projectmanager.dragard.org/ProjectEndpointImpl/createProjectResponse")
    @RequestWrapper(localName = "createProject", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.CreateProject")
    @ResponseWrapper(localName = "createProjectResponse", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.CreateProjectResponse")
    @WebResult(name = "response", targetNamespace = "")
    public org.dragard.projectmanager.endpoint.Response createProject(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    );

    @WebMethod
    @Action(input = "http://endpoint.projectmanager.dragard.org/ProjectEndpointImpl/updateProjectRequest", output = "http://endpoint.projectmanager.dragard.org/ProjectEndpointImpl/updateProjectResponse")
    @RequestWrapper(localName = "updateProject", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.UpdateProject")
    @ResponseWrapper(localName = "updateProjectResponse", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.UpdateProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.dragard.projectmanager.endpoint.Response updateProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebMethod
    @Action(input = "http://endpoint.projectmanager.dragard.org/ProjectEndpointImpl/deleteProjectRequest", output = "http://endpoint.projectmanager.dragard.org/ProjectEndpointImpl/deleteProjectResponse")
    @RequestWrapper(localName = "deleteProject", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.DeleteProject")
    @ResponseWrapper(localName = "deleteProjectResponse", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.DeleteProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.dragard.projectmanager.endpoint.Response deleteProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.projectmanager.dragard.org/ProjectEndpointImpl/persistProjectRequest", output = "http://endpoint.projectmanager.dragard.org/ProjectEndpointImpl/persistProjectResponse")
    @RequestWrapper(localName = "persistProject", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.PersistProject")
    @ResponseWrapper(localName = "persistProjectResponse", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.PersistProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.dragard.projectmanager.endpoint.Response persistProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<org.dragard.projectmanager.endpoint.Project> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
