package org.dragard.projectmanager.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-04T15:14:28.692+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.projectmanager.dragard.org/", name = "TaskEndpointImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface TaskEndpointImpl {

    @WebMethod
    @Action(input = "http://endpoint.projectmanager.dragard.org/TaskEndpointImpl/getViewTaskRequest", output = "http://endpoint.projectmanager.dragard.org/TaskEndpointImpl/getViewTaskResponse")
    @RequestWrapper(localName = "getViewTask", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.GetViewTask")
    @ResponseWrapper(localName = "getViewTaskResponse", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.GetViewTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.dragard.projectmanager.endpoint.Response getViewTask(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    );

    @WebMethod
    @Action(input = "http://endpoint.projectmanager.dragard.org/TaskEndpointImpl/updateTaskRequest", output = "http://endpoint.projectmanager.dragard.org/TaskEndpointImpl/updateTaskResponse")
    @RequestWrapper(localName = "updateTask", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.UpdateTask")
    @ResponseWrapper(localName = "updateTaskResponse", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.UpdateTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.dragard.projectmanager.endpoint.Response updateTask(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    );

    @WebMethod
    @Action(input = "http://endpoint.projectmanager.dragard.org/TaskEndpointImpl/createTaskRequest", output = "http://endpoint.projectmanager.dragard.org/TaskEndpointImpl/createTaskResponse")
    @RequestWrapper(localName = "createTask", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.CreateTask")
    @ResponseWrapper(localName = "createTaskResponse", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.CreateTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.dragard.projectmanager.endpoint.Response createTask(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "projectId", targetNamespace = "")
        java.lang.String projectId,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    );

    @WebMethod
    @Action(input = "http://endpoint.projectmanager.dragard.org/TaskEndpointImpl/deleteTaskRequest", output = "http://endpoint.projectmanager.dragard.org/TaskEndpointImpl/deleteTaskResponse")
    @RequestWrapper(localName = "deleteTask", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.DeleteTask")
    @ResponseWrapper(localName = "deleteTaskResponse", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.DeleteTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.dragard.projectmanager.endpoint.Response deleteTask(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    );

    @WebMethod
    @Action(input = "http://endpoint.projectmanager.dragard.org/TaskEndpointImpl/persistTaskRequest", output = "http://endpoint.projectmanager.dragard.org/TaskEndpointImpl/persistTaskResponse")
    @RequestWrapper(localName = "persistTask", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.PersistTask")
    @ResponseWrapper(localName = "persistTaskResponse", targetNamespace = "http://endpoint.projectmanager.dragard.org/", className = "org.dragard.projectmanager.endpoint.PersistTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.dragard.projectmanager.endpoint.Response persistTask(
        @WebParam(name = "elements", targetNamespace = "")
        java.util.List<org.dragard.projectmanager.endpoint.Task> elements,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    );
}
