package org.dragard.projectmanager.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-02T16:52:18.624+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "TaskEndpointImplService",
                  wsdlLocation = "http://localhost:9090/task-manager/task?wsdl",
                  targetNamespace = "http://endpoint.projectmanager.dragard.org/")
public class TaskEndpointImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.projectmanager.dragard.org/", "TaskEndpointImplService");
    public final static QName TaskEndpointImplPort = new QName("http://endpoint.projectmanager.dragard.org/", "TaskEndpointImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9090/task-manager/task?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TaskEndpointImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:9090/task-manager/task?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TaskEndpointImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TaskEndpointImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskEndpointImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TaskEndpointImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TaskEndpointImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TaskEndpointImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TaskEndpointImpl
     */
    @WebEndpoint(name = "TaskEndpointImplPort")
    public TaskEndpointImpl getTaskEndpointImplPort() {
        return super.getPort(TaskEndpointImplPort, TaskEndpointImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskEndpointImpl
     */
    @WebEndpoint(name = "TaskEndpointImplPort")
    public TaskEndpointImpl getTaskEndpointImplPort(WebServiceFeature... features) {
        return super.getPort(TaskEndpointImplPort, TaskEndpointImpl.class, features);
    }

}
